default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: analise_development

test:
  <<: *default
  database: analise_test

production:
  <<: *default
  database: analise_production
  username: root
  password: <%= ENV['TEA_DATABASE_PASSWORD'] %>
